version: "0.2"
services:
  app-ktor:
    image: app-ktor:latest
    ports:
      - "8888:8080"
    environment:
      MODE: "TEST"
      PG_URL: ""
      PG_USER: ""
      PG_PASSWORD: ""
      PG_MAXIMUM_POOL_SIZE: ""
      PG_MINIMUM_IDLE: ""
      PG_IDLE_TIMEOUT: ""
      PG_CONNECTION_TIMEOUT: ""
